version: '2'
services:
  node:
    image: node:alpine
    container_name: node-container
    ports:
     - "3000:3000"
    volumes:
      - ./:/usr/src/app
    working_dir:
      "/usr/src/app"
    entrypoint: /usr/src/app/entrypoint
  mysql:
    image: mysql/mysql-server
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_HOST=%
    volumes:
    - ./db.sql:/docker-entrypoint-initdb.d/db.sql
